---
description: |
date: 2023-10-02
layout: single
---

```{css echo = FALSE}
.button_custom {
  font-family: "Commissioner";
  font-size: 18px;
  color: #242424;
  border: 1px solid #242424;
  padding: 8px 24px;
  border-radius: 3px;
  background-color: white;
}

.button_custom:hover {
  background-color: #242424;
  color: white;
  border: 1px solid #242424;
  border-radius: 3px;
}
```

<font size = "4">

<h2> 2024 </h2>

Kumagai, **Goodman**, Villasenor-Derbez, Schoeman, Cavanuagh, Bell, Micheli, De Leo, & Arafeh-Dalmau (2024). *Marine protected areas that preserve trophic cascades promote resilience of kelp forests to marine heatwaves*, Global Change Biology

<a href="https://doi.org/10.1111/gcb.17620"><button class="btn btn-primary button_custom"><i class="fa fa-file"></i> Paper</button></a>

Gissi, **Goodman**, Elahi, McDevitt-Irwin, Arnoldi, Arafeh-Dalmau, Knight, Jacobson, Palmisciano, Tillman, De Leo, & Micheli (2024). *Sex-specific variation in species interactions matters in ecological communities*, Trends in Ecology & Evolution

<a href="https://doi.org/10.1016/j.tree.2024.07.006"><button class="btn btn-primary button_custom"><i class="fa fa-file"></i> Paper</button></a>

Rempel, Bodwin, Burkepile, Adam, Altieri, Barton, **Goodman**, Lamore, Lippert, Marroquin, O'Rourke, VanderBloomer, & Ruttenberg (2024). *Ecological drivers of parrotfish predation vary across spatial scales*, Marine Ecology Progress Series

<a href="https://doi.org/10.3354/meps14633"><button class="btn btn-primary button_custom"><i class="fa fa-file"></i> Paper</button></a>

<br/>

<h2> 2023 </h2>

O'Leary, Bockmon, **Goodman**, Grimsditch, Madej, Mohammed, & Tyburczy (2023). *Conserving and Managing Estuaries during Climate Change*, In: Climate Change and Estuaries

<a href="https://www.taylorfrancis.com/chapters/edit/10.1201/9781003126096-35/conserving-managing-estuaries-climate-change-leary-bockmon-goodman-grimsditch-madej-mohammed-tyburczy"><button class="btn btn-primary button_custom"><i class="fa fa-file"></i> Book chapter</button></a> 


Faiad, Williams, **Goodman**, ..., Wood (2023). *Temperature affects predation of schistosome-competent snails by a novel invader, the marbled crayfish Procambarus virginalis*, PLoS One

<a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0290615"><button class="btn btn-primary button_custom"><i class="fa fa-file"></i> Paper</button></a> <b>&emsp;</b>
<a href="https://github.com/wood-lab/Faiad_et_al_2023_PLoS_One"><button class="btn btn-primary button_custom"><i class="fa fa-code"></i> Code</button></a>

<br/>

<h2> 2022 </h2>

**Goodman**, Carroll, Brodie, Grrüss, Thorson, Kotwicki, Holsman, Selden, Hazen, & De Leo (2022). *Shifting fish distributions impact predation intensity in a sub‐Arctic ecosystem*, Ecography

<a href="https://onlinelibrary.wiley.com/doi/full/10.1111/ecog.06084"><button class="btn btn-primary button_custom"><i class="fa fa-file"></i> Paper</button></a> <b>&emsp;</b>
<a href="https://github.com/mcgoodman/Goodman-et-al_2022_Ecography"><button class="btn btn-primary button_custom"><i class="fa fa-code"></i> Code</button></a>


Andrzejaczek, Lucas, **Goodman**, ..., et al. (2022). *Diving into the vertical dimension of elasmobranch movement ecology*, Science Advances

<a href="https://www.science.org/doi/full/10.1126/sciadv.abo1754"><button class="btn btn-primary button_custom"><i class="fa fa-file"></i> Paper</button></a> <b>&emsp;</b>
<a href="https://github.com/mcgoodman/shark-vertical-overlap"><button class="btn btn-primary button_custom"><i class="fa fa-code"></i> Code</button></a>


McCalla, Phillips, Anderson, Voorhees, Siegler, Faulkenberry, **Goodman**, Deng, & Tjeerdema (2022). *Effectiveness of a Constructed Wetland with Carbon Filtration in Reducing Pesticides Associated with Agricultural Runoff*, Archives of Environmental Contamination and Toxicology

<a href="https://link.springer.com/article/10.1007/s00244-021-00909-0"><button class="btn btn-primary button_custom"><i class="fa fa-file"></i> Paper</button></a> <b>&emsp;</b>

<br/>

<h2> 2021 </h2>

O’Leary, **Goodman**, Walter, Willits, Pondella, & Stephens (2021). *Effects of estuary-wide seagrass loss on fish populations*, Estuaries and Coasts

<a href="https://link.springer.com/article/10.1007/s12237-021-00917-2"><button class="btn btn-primary button_custom"><i class="fa fa-file"></i> Paper</button></a> <b>&emsp;</b>
<a href="https://github.com/mcgoodman/OLeary-et-al_2020_ESCO"><button class="btn btn-primary button_custom"><i class="fa fa-code"></i> Code</button></a>

<br/>

<h2> 2020 </h2>

O’Leary, **Goodman**, Tuda, Machumu,  & West (2020). *Opportunities and challenges in achieving co-management in marine protected areas in East Africa: a comparative case study*, Journal of the Indian Ocean Region

<a href="https://www.tandfonline.com/doi/full/10.1080/19480881.2020.1825201"><button class="btn btn-primary button_custom"><i class="fa fa-file"></i> Paper</button></a> <b>&emsp;</b>


Hart, **Goodman**, Walter, Rogers-Bennett, Shum, Garrett, Watanabe, & O'leary (2020). *Abalone Recruitment in Low-Density and Aggregated Populations Facing Climatic Stress*, Journal of Shellfish Research

<a href="https://doi.org/10.2983/035.039.0218"><button class="btn btn-primary button_custom"><i class="fa fa-file"></i> Paper</button></a> <b>&emsp;</b>

<br/>

<h2> 2019 </h2>

**Goodman**, Hannah, & Ruttenberg (2019). *The relationship between geographic range extent, sea surface temperature and adult traits in coastal temperate fishes*, Journal of Biogeography

<a href="https://onlinelibrary.wiley.com/doi/full/10.1111/jbi.13595"><button class="btn btn-primary button_custom"><i class="fa fa-file"></i> Paper</button></a> <b>&emsp;</b>
<a href="https://datadryad.org/stash/dataset/doi:10.5061/dryad.8n4pn0b"><button class="btn btn-primary button_custom"><i class="fa fa-database"></i> Data</button></a>

<br/>