---
title: "Predator-prey ecology"
subtitle: "I'm interested in the many ways climate mediate species interactions - including by altering spatial overlap among interacting species, predator bioenergetics, and animal behavior."
excerpt: "I'm interested in the many ways climate mediate species interactions - including by altering spatial overlap among interacting species, predator bioenergetics, and animal behavior."
date: 2023-10-03
draft: false
layout: single
---

## Range shifts alter predator-prey interactions at large scales

-----------

**Goodman**, Carroll, Brodie, Grrüss, Thorson, Kotwicki, Holsman, Selden, Hazen, & De Leo (2022). *Shifting fish distributions impact predation intensity in a sub‐Arctic ecosystem*, Ecography

<a href="https://onlinelibrary.wiley.com/doi/full/10.1111/ecog.06084"><button class="btn btn-primary button_custom"><i class="fa fa-file"></i> Paper</button></a> <b>&emsp;</b>
<a href="https://github.com/mcgoodman/Goodman-et-al_2022_Ecography"><button class="btn btn-primary button_custom"><i class="fa fa-code"></i> Code</button></a>

<br/>

Many studies in marine ecosystems have documented species range shifts in  response to climate change, and many more have used species distribution models to project species ranges under future conditions. Presumably, as the spatial overlap between fish and their predators changes over time, so too should predation rates (integrated across space) - but how well can we predict trophic interactions from predator-prey overlap?

In this study, we employed spatiotemporal models to characterize decadal-scale changes in spatial overlap between the distribution of juvenile walleye pollock and the distributions of four of its groundfish predators: arrowtooth flounder, Pacific cod, Pacific halibut, and adult walleye pollock. These fishes represent ecologically and commercially important species in a rapidly changing  sub-Arctic ecosystem, the eastern Bering Sea, Alaska, USA. 

<br/>

![During years with extensive sea ice, melting sea ice results in the formation of a deep “cold pool” of water below 2 °C in the Eastern Bering Sea (EBS). The cold pool can restrict the movement of some predators into the northeast EBS shelf, such that years with less extensive cold pools may result in greater spatial overlap between juvenile pollock and their predators. For example, area overlap between juvenile pollock and flounder was about 15% higher during 2015, when the cold pool was receded (~124,500 km2), than in 2009, when it was more extensive (~333,000 km2). Smoothed 2 °C and 0 °C isotherms are shown as solid and dashed lines, respectively.](featured.png)

<br/>

We then examined whether changes in spatial overlap corresponded to changes in predation, using spatiotemporal models of predator stomach contents. We found marked shifts in spatial overlap between juvenile pollock and two predators (arrowtooth flounder and Pacific halibut) over 34 years, with changes in overlap corresponding to increases in population-scale predation pressure. By contrast, we did not find clear relationships between spatial overlap and predation for Pacific cod and adult pollock, the two predators for which juvenile  pollock constitute a much smaller diet proportion.

Our findings highlight the complexity of predicting predation dynamics for generalist marine species and suggest a need for better process-based methods for understanding the potential future ecological impacts of coupled species range shifts. However, our results also show that simple metrics of spatial overlap between relatively specialized predators and their prey offer promise as a means to integrate predictions from species distribution models into ecosystem-based fisheries management.

<br/>

![For each species of predator, we used VAST (Vector Autoregressive Spatio-Temporal) models to generate annual estimates of spatial overlap with, and predation on, juvenile pollock. Predation is measured annually as both the total biomass of juvenile pollock consumed (in tonnes) by each species of predator across the EBS annually (“total predation”), and as the average biomass of juvenile pollock consumed per biomass of predator (“relative biomass”).](diagram.png)

<br/>


## Perspective: Sex-specific variation in species interactions

-----------

Gissi, **Goodman**, Elahi, McDevitt-Irwin, Arnoldi, Arafeh-Dalmau, Knight, Jacobson, Palmisciano, Tillman, De Leo, & Micheli (2024). *Sex-specific variation in species interactions matters in ecological communities*, Trends in Ecology & Evolution

<a href="https://doi.org/10.1016/j.tree.2024.07.006"><button class="btn btn-primary button_custom"><i class="fa fa-file"></i> Paper</button></a>

<br/>

Biological sex affects organismal morphology, foraging behavior, and spatial distribution, yet marine ecosystem models rarely incorporate species interactions structured by sex. In this paper, we conducted a literature review to assess the frequency with which differences in species interactions are examined by sex and how often these differences were found. 

We found evidence of widespread sex-based variation in species interactions, and that sex-based variation in species interactions is likely to affect ecosystem structure and functioning via multiple trophic and nontrophic pathways.

<br/> 

![We examined these differences using Pacific coast kelp forests as a model. (A) A model of Northeast Pacific kelp forest ecosystems as a linear chain of trophic effects, where a reduction in kelp’s abundance was attributed to increased predation by killer whales on sea otters, a keystone predator that suppresses grazing outbreaks by urchin and thus deforestation. (B) Evolution of the model, updating the trophic cascade to reflect other species interactions and the role of bottom-up processes. (C) Emerging model with sex-specific variations in species interactions represented through existing empirical research for a composite food web of kelps in temperate regions. Black unbroken arrows represent trophic interactions, black broken arrows represent nontrophic interactions, and grey arrows represent known trophic interactions for which there is no evidence about sex-specific influences; thickness represents the intensity of effects by or on males and females.](Kelp_forest_web.png)


## Other research

-----------

Faiad, Williams, **Goodman**, ..., Wood (2023). *Temperature affects predation of schistosome-competent snails by a novel invader, the marbled crayfish Procambarus virginalis*, PLoS One

<a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0290615"><button class="btn btn-primary button_custom"><i class="fa fa-file"></i> Paper</button></a> <b>&emsp;</b>
<a href="https://github.com/wood-lab/Faiad_et_al_2023_PLoS_One"><button class="btn btn-primary button_custom"><i class="fa fa-code"></i> Code</button></a>

<br/>


Rempel, Bodwin, Burkepile, Adam, Altieri, Barton, **Goodman**, Lamore, Lippert, Marroquin, O'Rourke, VanderBloomer, & Ruttenberg (2024). *Ecological drivers of parrotfish predation vary across spatial scales*, Marine Ecology Progress Series

<a href="https://doi.org/10.3354/meps14633"><button class="btn btn-primary button_custom"><i class="fa fa-file"></i> Paper</button></a>

<br/>